MOVIE RECOMMENDATION SYSTEM`

In [2]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import os

In [3]:
display(os.getcwd())

'C:\\Users\\shour\\Jupyter Notebooks'

In [4]:
os.chdir(r"E:\Machine Learning\ML Day19- Projects\PRJ Movie Recommendation System")
movies_data = pd.read_csv('movies.csv')
movies_data.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [5]:
display(movies_data.shape)

(4803, 24)

In [6]:
selected_features = ['genres', 'keywords', 'tagline', 'cast', 'director']
print(selected_features)

['genres', 'keywords', 'tagline', 'cast', 'director']

In [7]:
display(movies_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

None

In [8]:
display(movies_data.isna().sum())

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [9]:
display(movies_data[selected_features].head())

,genres,keywords,tagline,cast,director
0,Action Adventure Fantasy Science Fiction,culture clash future space war space colony so...,Enter the World of Pandora.,Sam Worthington Zoe Saldana Sigourney Weaver S...,James Cameron
1,Adventure Fantasy Action,ocean drug abuse exotic island east india trad...,"At the end of the world, the adventure begins.",Johnny Depp Orlando Bloom Keira Knightley Stel...,Gore Verbinski
2,Action Adventure Crime,spy based on novel secret agent sequel mi6,A Plan No One Escapes,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,Sam Mendes
3,Action Crime Drama Thriller,dc comics crime fighter terrorist secret ident...,The Legend Ends,Christian Bale Michael Caine Gary Oldman Anne ...,Christopher Nolan
4,Action Adventure Science Fiction,based on novel mars medallion space travel pri...,"Lost in our world, found in another.",Taylor Kitsch Lynn Collins Samantha Morton Wil...,Andrew Stanton

In [10]:
display(movies_data[selected_features].isna().sum())

genres       28
keywords    412
tagline     844
cast         43
director     30
dtype: int64

In [11]:
for feature in selected_features:
    movies_data[feature] = movies_data[feature].fillna('')
display(movies_data.head())

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [12]:
combined_features = movies_data['genres']+''+movies_data['keywords']+''+movies_data['tagline']+''+movies_data['cast']+''+movies_data['director']
display(combined_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object

In [13]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

In [14]:
display(feature_vectors.shape)
print(feature_vectors)

(4803, 27580)

  (0, 3583)	0.16941894714909375
  (0, 20729)	0.2738578969459924
  (0, 16614)	0.15696073877453268
  (0, 14550)	0.2236809363648068
  (0, 23267)	0.16128139780622516
  (0, 26547)	0.19638671147741732
  (0, 22464)	0.20207089568711745
  (0, 21487)	0.21550128478931546
  (0, 27540)	0.19771357974524176
  (0, 27182)	0.23480088356130552
  (0, 21521)	0.1562356665943368
  (0, 18558)	0.2612168335104853
  (0, 18164)	0.08690831799482265
  (0, 27161)	0.1261988657937151
  (0, 24197)	0.07518543993419265
  (0, 22778)	0.2738578969459924
  (0, 4676)	0.2452909770424961
  (0, 26334)	0.13059723071916296
  (0, 22916)	0.33668756406929184
  (0, 10193)	0.16532432420812987
  (0, 4456)	0.21799675215510664
  (0, 9304)	0.2738578969459924
  (0, 21836)	0.09966592997173944
  (0, 8936)	0.11806131645084653
  (0, 444)	0.09109355212252294
  :	:
  (4801, 5449)	0.31510541707008866
  (4801, 22170)	0.31510541707008866
  (4801, 27361)	0.31510541707008866
  (4801, 27513)	0.3005604008026175
  (4801, 8121)	0.2611505149930138
  (4801, 758)	0.19369913462690624
  (4801, 11776)	0.3005604008026175
  (4801, 18790)	0.22450140828104795
  (4801, 2511)	0.16619755360453184
  (4801, 17791)	0.15702571586793676
  (4801, 12846)	0.1232063996421506
  (4802, 7770)	0.28212235292045307
  (4802, 11874)	0.5642447058409061
  (4802, 10640)	0.28212235292045307
  (4802, 6978)	0.28212235292045307
  (4802, 3569)	0.2526933433912742
  (4802, 9174)	0.23381507827213685
  (4802, 5847)	0.2598601666162226
  (4802, 11042)	0.2245754361399493
  (4802, 20664)	0.1718311116708895
  (4802, 2027)	0.19514642661077047
  (4802, 5354)	0.2196244946235084
  (4802, 8313)	0.1713172199751922
  (4802, 3128)	0.17288424030654004
  (4802, 7626)	0.17686850692938538

In [15]:
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.06865296 0.01492221 ... 0.         0.         0.        ]
 [0.06865296 1.         0.02799128 ... 0.01243107 0.         0.        ]
 [0.01492221 0.02799128 1.         ... 0.         0.         0.        ]
 ...
 [0.         0.01243107 0.         ... 1.         0.         0.        ]
 [0.         0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [16]:
display(similarity.shape)

(4803, 4803)

In [17]:
movie_name = input("Enter Your Favourite Movie : ")

Enter Your Favourite Movie : BATMAN

In [18]:
list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [19]:
len(list_of_all_titles)

4803

In [20]:
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['TMNT']

In [21]:
close_match = find_close_match[0]
print(close_match)

TMNT

In [22]:
index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

1382

In [23]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.036567934745542055), (1, 0.016110208886541015), (2, 0.009498904340833718), (3, 0.02587624981716026), (4, 0.009029324267583414), (5, 0.0), (6, 0.028180303704604732), (7, 0.04892460741566832), (8, 0.009718726596573628), (9, 0.009299559111620035), (10, 0.034536185238873675), (11, 0.008550726985299559), (12, 0.00939902444020257), (13, 0.008926825589607728), (14, 0.030406237651804384), (15, 0.07379273404541656), (16, 0.06032902289210043), (17, 0.029415932026375408), (18, 0.029074356769414753), (19, 0.00808176058359114), (20, 0.00891411993699654), (21, 0.0), (22, 0.0088175660528699), (23, 0.007950100902368083), (24, 0.008653075508577806), (25, 0.0), (26, 0.05203687694293091), (27, 0.008334384274500246), (28, 0.008970990458663983), (29, 0.009762230332804895), (30, 0.009219986769507537), (31, 0.009160939681990166), (32, 0.0), (33, 0.03515431131858308), (34, 0.03685749073266727), (35, 0.0), (36, 0.0), (37, 0.038830950826118996), (38, 0.009429944598633574), (39, 0.009163000905385398), (40, 0.0352904381178987), (41, 0.008748594183294671), (42, 0.017906681694414835), (43, 0.0), (44, 0.029811825424671767), (45, 0.0), (46, 0.00867579881655727), (47, 0.009994381941935752), (48, 0.0), (49, 0.0), (50, 0.11382515530909582), (51, 0.0), (52, 0.0), (53, 0.0190105824020471), (54, 0.025509400549953272), (55, 0.05793709201833548), (56, 0.010247114751306515), (57, 0.030140269338107466), (58, 0.02112897236517538), (59, 0.008950299640009799), (60, 0.019174863505393956), (61, 0.0), (62, 0.0), (63, 0.07071062731134053), (64, 0.0), (65, 0.02444693361399382), (66, 0.04030865861361299), (67, 0.028414312685192823), (68, 0.0), (69, 0.015820985756518087), (70, 0.06021503695476884), (71, 0.011477179383306158), (72, 0.044116371791294746), (73, 0.027864776210409673), (74, 0.0), (75, 0.02920551804362095), (76, 0.009426384655845887), (77, 0.06462588932048775), (78, 0.010364155620073772), (79, 0.008304782765848296), (80, 0.009717027577951648), (81, 0.007839759759486148), (82, 0.0), (83, 0.009837051835395518), (84, 0.007859989005708438), (85, 0.05229126880212534), (86, 0.03644578123248539), (87, 0.009255696792822796), (88, 0.09346747801567871), (89, 0.04676601401327338), (90, 0.026697835729776676), (91, 0.009011502432119685), (92, 0.0371698365413029), (93, 0.0), (94, 0.0), (95, 0.023344161834669815), (96, 0.01172147857423043), (97, 0.007723453602285489), (98, 0.008656697518418358), (99, 0.0379801020002844), (100, 0.0), (101, 0.02198424073475169), (102, 0.009725421943237696), (103, 0.015287309198485989), (104, 0.009987793160926262), (105, 0.0), (106, 0.034460898933957804), (107, 0.009635744279657648), (108, 0.0), (109, 0.007653104589469023), (110, 0.0), (111, 0.009780312601990693), (112, 0.009228393810341648), (113, 0.009297368447127693), (114, 0.008540233866104323), (115, 0.023900631963438675), (116, 0.02176844255442892), (117, 0.02827941461095332), (118, 0.1342504998677923), (119, 0.10057684829482719), (120, 0.02506864620792617), (121, 0.014355852284076293), (122, 0.009893164606224277), (123, 0.008771985429552003), (124, 0.024882455468880245), (125, 0.07979413625521037), (126, 0.008796107260706756), (127, 0.009669703427243102), (128, 0.0), (129, 0.009328431857312122), (130, 0.024880951413966308), (131, 0.010076524804938652), (132, 0.0), (133, 0.032776516351229676), (134, 0.009342221669357617), (135, 0.014321354706015348), (136, 0.04739209874605156), (137, 0.052045421173174775), (138, 0.008849197563728012), (139, 0.008169711550842831), (140, 0.0), (141, 0.02754014229422056), (142, 0.036096654299524945), (143, 0.009526924710465649), (144, 0.042739019922208264), (145, 0.06715178909174155), (146, 0.01655252981837677), (147, 0.008320946510668172), (148, 0.0), (149, 0.0), (150, 0.03862762446454644), (151, 0.009009341205786062), (152, 0.10313788191521436), (153, 0.0), (154, 0.017850540998051747), (155, 0.0), (156, 0.0), (157, 0.009991981333291051), (158, 0.0), (159, 0.0), (160, 0.057852579348617025), (161, 0.0), (162, 0.0), (163, 0.02300998765014688), (164, 0.027791490858306657), (165, 0.0), (166, 0.010858350764115572), (167, 0.02580480084418018), (168, 0.026899159641573217), (169, 0.06987497411084885), (170, 0.007730836674445165), (171, 0.0), (172, 0.008930968797473854), (173, 0.02877674165049432), (174, 0.020707101696939876), (175, 0.008654114724058326), (176, 0.02273881338771584), (177, 0.019405060669513252), (178, 0.022985651768666796), (179, 0.02780338826891044), (180, 0.0), (181, 0.10457574981690294), (182, 0.0), (183, 0.00964219235991986), (184, 0.02624928979797013), (185, 0.009087295654964186), (186, 0.03516038282664128), (187, 0.025860552326423397), (188, 0.0), (189, 0.0), (190, 0.034102870201350985), (191, 0.009030054275182709), (192, 0.0), (193, 0.05279443255389024), (194, 0.01751162040277909), (195, 0.014828948988102424), (196, 0.024979036042551965), (197, 0.009417801318435162), (198, 0.02667937586976048), (199, 0.008451958026811677), (200, 0.009466951314028494), (201, 0.0), (202, 0.03248438883278803), (203, 0.0316457713889701), (204, 0.0), (205, 0.021904349245275324), (206, 0.009072933760648487), (207, 0.008517381095592089), (208, 0.008963640842434102), (209, 0.0), (210, 0.022799299291403435), (211, 0.005950143441796444), (212, 0.008909956291046302), (213, 0.01012751585159527), (214, 0.0), (215, 0.051675442911129375), (216, 0.00909774830946333), (217, 0.0), (218, 0.0), (219, 0.010061830672246232), (220, 0.008313809195495568), (221, 0.02850957891472617), (222, 0.0), (223, 0.0), (224, 0.0), (225, 0.05697260915734598), (226, 0.0067878232430989725), (227, 0.0), (228, 0.008681018313188713), (229, 0.009331591889480198), (230, 0.007766828388988771), (231, 0.023617466190084847), (232, 0.008493011753796926), (233, 0.007923145171818243), (234, 0.034531475653876646), (235, 0.014827077843844651), (236, 0.0), (237, 0.008821158006411322), (238, 0.03852088100256574), (239, 0.0), (240, 0.03357864025746912), (241, 0.07823625196898071), (242, 0.009842732926962468), (243, 0.014900220557307803), (244, 0.0), (245, 0.032386658653451174), (246, 0.06964112529834744), (247, 0.0), (248, 0.006366000487676831), (249, 0.009060136740096337), (250, 0.0), (251, 0.0), (252, 0.08833852367185173), (253, 0.0), (254, 0.07375706095087892), (255, 0.021412031398633173), (256, 0.009102365494697), (257, 0.036752847991546524), (258, 0.05171349267331493), (259, 0.008472853629780824), (260, 0.0), (261, 0.0), (262, 0.009065357289013523), (263, 0.031816677106650884), (264, 0.023366452523438146), (265, 0.07170427704517993), (266, 0.024151752828723096), (267, 0.007838579996460007), (268, 0.08501044330279128), (269, 0.016151451792451484), (270, 0.010040071613811822), (271, 0.0), (272, 0.005759059091723293), (273, 0.07599405469613213), (274, 0.0), (275, 0.0), (276, 0.009403930440419062), (277, 0.009156831332172044), (278, 0.0), (279, 0.02736318240350771), (280, 0.011690058446809157), (281, 0.0), (282, 0.0), (283, 0.03904684812825703), (284, 0.006129682959143923), (285, 0.005455675326613449), (286, 0.0), (287, 0.0), (288, 0.0464417586158937), (289, 0.056460464342286076), (290, 0.009911671111222637), (291, 0.0169228813657123), (292, 0.0076260878660168495), (293, 0.0), (294, 0.02951807826527335), (295, 0.0), (296, 0.021778076303723623), (297, 0.04179098905484309), (298, 0.012620740716848334), (299, 0.012372313570698212), (300, 0.028819337455082094), (301, 0.0), (302, 0.02817805198094639), (303, 0.0), (304, 0.0), (305, 0.02746149988350033), (306, 0.015542703242874531), (307, 0.009047600376561464), (308, 0.010730342766580707), (309, 0.006695598358660292), (310, 0.008946052818699415), (311, 0.006355338339505918), (312, 0.008282499274118754), (313, 0.0), (314, 0.012050824386089513), (315, 0.008227172654725915), (316, 0.0), (317, 0.0), (318, 0.02199943963313249), (319, 0.006372019872509108), (320, 0.0), (321, 0.027912732175345303), (322, 0.009840932947323569), (323, 0.07850400490905995), (324, 0.061357470132870184), (325, 0.03224265494833865), (326, 0.0), (327, 0.0), (328, 0.028400838523027654), (329, 0.009121441194971908), (330, 0.00907096968946023), (331, 0.007073345350000521), (332, 0.007611823606936668), (333, 0.0), (334, 0.00878042544914088), (335, 0.0), (336, 0.0479964144771496), (337, 0.0), (338, 0.02500760694063841), (339, 0.03018314773421396), (340, 0.027598384322517332), (341, 0.009040971328843352), (342, 0.03643104192583434), (343, 0.024776393358474626), (344, 0.017421974757377712), (345, 0.01978622499820497), (346, 0.02422785458475899), (347, 0.028211730188412155), (348, 0.024442998385440097), (349, 0.014625541094662397), (350, 0.06917334159685709), (351, 0.0), (352, 0.01740099655571456), (353, 0.0), (354, 0.05208647142401178), (355, 0.0), (356, 0.022181858848483275), (357, 0.0), (358, 0.04840786563528134), (359, 0.03352210617570377), (360, 0.0), (361, 0.029321952277855255), (362, 0.05947441256955038), (363, 0.0), (364, 0.005263179306270863), (365, 0.0), (366, 0.018149925193150184), (367, 0.03493739779340704), (368, 0.029088138601639946), (369, 0.0078437988147488), (370, 0.027479031336666012), (371, 0.0), (372, 0.010933972236182029), (373, 0.0), (374, 0.030104212232678416), (375, 0.005595292564800546), (376, 0.0), (377, 0.02662661983354594), (378, 0.0), (379, 0.008501225721149785), (380, 0.0), (381, 0.0), (382, 0.0), (383, 0.023467699452832506), (384, 0.008816920707685798), (385, 0.017810056787125977), (386, 0.0), (387, 0.040614826004665504), (388, 0.0), (389, 0.008913997689881095), (390, 0.045494373769219304), (391, 0.0299752030573652), (392, 0.0), (393, 0.03504280296003437), (394, 0.0), (395, 0.004997983808883399), (396, 0.024679488834082136), (397, 0.005943215592126205), (398, 0.011777659207383774), (399, 0.023785394278591054), (400, 0.008221168412166566), (401, 0.0), (402, 0.015483301801704695), (403, 0.013987652623625065), (404, 0.011957505379900004), (405, 0.009850736863133836), (406, 0.01661823919108666), (407, 0.0), (408, 0.0), (409, 0.0), (410, 0.01460780076838937), (411, 0.03804421653044088), (412, 0.008866175237066577), (413, 0.006177499375824697), (414, 0.13141310260771677), (415, 0.013209098010697185), (416, 0.005593849962764159), (417, 0.005383639388790059), (418, 0.006085856352615084), (419, 0.01023625512643673), (420, 0.009176408744645542), (421, 0.052817682827589536), (422, 0.028336115219557822), (423, 0.0), (424, 0.08791177200645697), (425, 0.010105204252564611), (426, 0.008827473124632534), (427, 0.0), (428, 0.04106874568584698), (429, 0.021529107520554102), (430, 0.049498913056555675), (431, 0.005895198303120835), (432, 0.0), (433, 0.019516606542711246), (434, 0.006399154357213997), (435, 0.005972610832970541), (436, 0.021709120394109837), (437, 0.00647478485370868), (438, 0.006684371593271774), (439, 0.029520466048179293), (440, 0.011308219197942206), (441, 0.024181106122975762), (442, 0.010167074191640965), (443, 0.005613303795827057), (444, 0.010670265482953474), (445, 0.0), (446, 0.0), (447, 0.029143823074542854), (448, 0.0), (449, 0.0), (450, 0.0059842462912399405), (451, 0.0), (452, 0.020362154927285693), (453, 0.041971321025614246), (454, 0.02187630368870952), (455, 0.04706319753692716), (456, 0.0), (457, 0.015008154159185237), (458, 0.024564485069253735), (459, 0.032911715739987656), (460, 0.02745744572547887), (461, 0.009980245297334722), (462, 0.0), (463, 0.0), (464, 0.04634345977622448), (465, 0.021024103389045874), (466, 0.019444271896153557), (467, 0.010304821169869341), (468, 0.011628209606828855), (469, 0.014077776080483488), (470, 0.0), (471, 0.07639828082217108), (472, 0.08311718908112244), (473, 0.005919540471560796), (474, 0.0), (475, 0.007703325819536745), (476, 0.0), (477, 0.0), (478, 0.009308463271824548), (479, 0.029501099112579275), (480, 0.0), (481, 0.02389368238356213), (482, 0.0), (483, 0.008188073133739378), (484, 0.018470243738201487), (485, 0.013775899305641836), (486, 0.022207049100010746), (487, 0.0), (488, 0.038634191248674774), (489, 0.0), (490, 0.008778846274739936), (491, 0.00847560925327236), (492, 0.007543694168843397), (493, 0.0), (494, 0.0244641786180817), (495, 0.008968763044698454), (496, 0.02107200259439864), (497, 0.013503111346235046), (498, 0.0), (499, 0.0), (500, 0.011777039454650428), (501, 0.037527828560371373), (502, 0.0), (503, 0.03521547257148008), (504, 0.03907280517911368), (505, 0.0), (506, 0.04069213166314051), (507, 0.03294356854484835), (508, 0.009366413084810586), (509, 0.023409591683204063), (510, 0.0), (511, 0.009678317927086146), (512, 0.0), (513, 0.007949300835663585), (514, 0.018857366764597577), (515, 0.00527100726660262), (516, 0.031120792315859853), (517, 0.0), (518, 0.04906468776035259), (519, 0.0), (520, 0.0), (521, 0.03154624767995607), (522, 0.005793535698926358), (523, 0.009476820797343077), (524, 0.0057939929746222444), (525, 0.043190970734855866), (526, 0.0), (527, 0.004928613832971289), (528, 0.0), (529, 0.0), (530, 0.007033187724292667), (531, 0.005499816156053957), (532, 0.015386075480402755), (533, 0.02564281774522527), (534, 0.03333989779959329), (535, 0.008773376153725186), (536, 0.014645152552549931), (537, 0.0), (538, 0.048471920215624485), (539, 0.029187512273087954), (540, 0.019189700889441247), (541, 0.0), (542, 0.0), (543, 0.02320605895375892), (544, 0.00892257390525082), (545, 0.036972961969711046), (546, 0.026324173440534178), (547, 0.0), (548, 0.011348238507178839), (549, 0.0), (550, 0.0), (551, 0.005710448195888662), (552, 0.005534717296501266), (553, 0.0), (554, 0.0), (555, 0.00572440489465366), (556, 0.023077691405327554), (557, 0.0), (558, 0.057304778904743905), (559, 0.0), (560, 0.0), (561, 0.09465832883099422), (562, 0.0), (563, 0.006079842342617727), (564, 0.0), (565, 0.034817139540390535), (566, 0.030771061752945174), (567, 0.006316829395995561), (568, 0.00881833366706066), (569, 0.033533611076877155), (570, 0.0), (571, 0.0), (572, 0.015507390868375813), (573, 0.04385030384843435), (574, 0.026214975268679414), (575, 0.0), (576, 0.0), (577, 0.008775009719970304), (578, 0.02369577936535992), (579, 0.0), (580, 0.0), (581, 0.031182680121275973), (582, 0.0), (583, 0.03260776038824508), (584, 0.032184374812820306), (585, 0.0), (586, 0.0), (587, 0.01583105632640876), (588, 0.0), (589, 0.06652475171876619), (590, 0.0), (591, 0.037873994161303985), (592, 0.008227320027715677), (593, 0.026480899916493193), (594, 0.015182524213901878), (595, 0.008582575990002438), (596, 0.016080390921237288), (597, 0.0), (598, 0.006235967599785736), (599, 0.0), (600, 0.011198428864839498), (601, 0.0), (602, 0.010472919803474702), (603, 0.0), (604, 0.031938728395718555), (605, 0.051606313161643505), (606, 0.011469997230852319), (607, 0.039991609044506875), (608, 0.011037076716815973), (609, 0.0), (610, 0.0), (611, 0.0), (612, 0.00975153946615679), (613, 0.01131236101068041), (614, 0.0197208181035385), (615, 0.11072766162152776), (616, 0.0), (617, 0.008359115994012725), (618, 0.013701062154628138), (619, 0.016210532286500233), (620, 0.0), (621, 0.0), (622, 0.0), (623, 0.0), (624, 0.0), (625, 0.0), (626, 0.0), (627, 0.02281519534781116), (628, 0.0), (629, 0.009805221977350549), (630, 0.005290570217541018), (631, 0.03634381794941033), (632, 0.0), (633, 0.0), (634, 0.0), (635, 0.02222993307867749), (636, 0.005573140720685202), (637, 0.0), (638, 0.011354676668160158), (639, 0.0), (640, 0.0), (641, 0.03416881182792873), (642, 0.0), (643, 0.009804959201590966), (644, 0.018739005226917717), (645, 0.009532851171491764), (646, 0.005121613578639388), (647, 0.0), (648, 0.0), (649, 0.0), (650, 0.0), (651, 0.006259010286734763), (652, 0.03917403864612788), (653, 0.006031416550576029), (654, 0.0), (655, 0.0), (656, 0.005731494222962845), (657, 0.02807950492948594), (658, 0.0), (659, 0.011919860892689151), (660, 0.011405518747581068), (661, 0.0), (662, 0.0), (663, 0.0), (664, 0.009190326874509979), (665, 0.02465927958378166), (666, 0.0), (667, 0.012343201965275555), (668, 0.03241923796737748), (669, 0.012613571030768808), (670, 0.0), (671, 0.008905925015655168), (672, 0.01172106320751006), (673, 0.12112898684516407), (674, 0.02271199255338864), (675, 0.017767890320297644), (676, 0.028342408208399394), (677, 0.0), (678, 0.0), (679, 0.005173388407219449), (680, 0.0), (681, 0.005237139074693811), (682, 0.012042037978117958), (683, 0.05177582652587938), (684, 0.010837103409844442), (685, 0.006092606986006607), (686, 0.02119022101763866), (687, 0.009263589920319495), (688, 0.021842127368275246), (689, 0.006844836517755649), (690, 0.0), (691, 0.008391462404032312), (692, 0.015490384392934596), (693, 0.023519893615794513), (694, 0.0), (695, 0.008216789961420497), (696, 0.012864177643429654), (697, 0.005895005386027582), (698, 0.08546991063727524), (699, 0.02944967872822912), (700, 0.00614868968904466), (701, 0.005679853539459236), (702, 0.0), (703, 0.03313029245694807), (704, 0.03328945644598954), (705, 0.005583532295066883), (706, 0.0), (707, 0.009343913166830649), (708, 0.0), (709, 0.0), (710, 0.00409173346123234), (711, 0.02487706665598924), (712, 0.0), (713, 0.024465910343237883), (714, 0.035462575937792076), (715, 0.0), (716, 0.025988470807585984), (717, 0.012061948371278098), (718, 0.0), (719, 0.023252803592801023), (720, 0.0), (721, 0.014495476195384112), (722, 0.017399178437462158), (723, 0.0), (724, 0.0), (725, 0.052413262764472016), (726, 0.006249460985122959), (727, 0.0), (728, 0.03616182473839242), (729, 0.0), (730, 0.023344271162756842), (731, 0.009510729484189491), (732, 0.010350118527952779), (733, 0.026044104842369294), (734, 0.0446289931956782), (735, 0.006138516857728861), (736, 0.0), (737, 0.02201653962510607), (738, 0.0), (739, 0.011100863509219254), (740, 0.0), (741, 0.0), (742, 0.03457606641224402), (743, 0.0), (744, 0.04711990174575753), (745, 0.0), (746, 0.008572681363520228), (747, 0.012453581047399097), (748, 0.006570400159442011), (749, 0.023196082714320828), (750, 0.0488317929563735), (751, 0.006260101769716191), (752, 0.005307272544552174), (753, 0.0), (754, 0.020893689031477005), (755, 0.03450942908750583), (756, 0.016957100972939544), (757, 0.0), (758, 0.012332926223181969), (759, 0.0), (760, 0.006661609078861903), (761, 0.01067059009712233), (762, 0.012583169859820923), (763, 0.0), (764, 0.0254261058624578), (765, 0.024063865055161664), (766, 0.024411693906242406), (767, 0.021730608023318825), (768, 0.0), (769, 0.058647199855299634), (770, 0.0), (771, 0.01942089126691087), (772, 0.0), (773, 0.01033345921218221), (774, 0.0), (775, 0.0), (776, 0.0), (777, 0.030115236210633237), (778, 0.10984839851322295), (779, 0.0), (780, 0.0), (781, 0.017192222188971425), (782, 0.016956415692035657), (783, 0.006244183922642202), (784, 0.00963509876372656), (785, 0.009294386556451022), (786, 0.01022410408338405), (787, 0.0), (788, 0.008617460605372081), (789, 0.005736948832474906), (790, 0.0), (791, 0.009771362827099417), (792, 0.005666474990783778), (793, 0.0060793235039232766), (794, 0.02668677552839394), (795, 0.005641158905603501), (796, 0.007732055947793186), (797, 0.0375298168301539), (798, 0.0), (799, 0.00842196264263207), (800, 0.008185190167987914), (801, 0.0), (802, 0.047088977848753794), (803, 0.0), (804, 0.018327486493829287), (805, 0.0), (806, 0.0), (807, 0.00622484687751932), (808, 0.009166809198274112), (809, 0.004986378907098993), (810, 0.00625575420945262), (811, 0.005881244457362982), (812, 0.026307235505312977), (813, 0.059223353330778605), (814, 0.02901117232551206), (815, 0.06127494670840666), (816, 0.01568612846908747), (817, 0.019995742389750902), (818, 0.0), (819, 0.0), (820, 0.006453214792977599), (821, 0.0), (822, 0.006567983206676246), (823, 0.0), (824, 0.0510046919083801), (825, 0.0), (826, 0.013015977848192263), (827, 0.0), (828, 0.0773033404985867), (829, 0.0), (830, 0.0716311063004192), (831, 0.007756533388388527), (832, 0.0), (833, 0.014301014912870148), (834, 0.009903863007387608), (835, 0.00639951640355449), (836, 0.008672522880416488), (837, 0.026136113309329547), (838, 0.0), (839, 0.0), (840, 0.011104511553364496), (841, 0.0), (842, 0.00996233535241684), (843, 0.0), (844, 0.0), (845, 0.0), (846, 0.06549812295594354), (847, 0.0), (848, 0.027727098484188), (849, 0.01143309561

In [24]:
len(similarity_score)

4803

In [25]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

[(1382, 1.0), (2442, 0.24651516947118915), (2060, 0.16824663361886188), (118, 0.1342504998677923), (414, 0.13141310260771677), (1134, 0.12860813456644896), (3201, 0.12801218101674447), (1830, 0.12486143515592743), (2196, 0.1245747621270463), (673, 0.12112898684516407), (3483, 0.11898723021820173), (50, 0.11382515530909582), (1029, 0.11260054928632601), (615, 0.11072766162152776), (778, 0.10984839851322295), (3539, 0.10940572517305086), (1796, 0.10767176385764121), (1821, 0.10691653904349463), (1112, 0.10555500758022925), (181, 0.10457574981690294), (152, 0.10313788191521436), (2988, 0.10310013841891048), (3309, 0.10295366184306784), (1961, 0.10196505910972128), (1174, 0.10176757778996359), (2181, 0.10059387438972131), (119, 0.10057684829482719), (4575, 0.09909554763250954), (2927, 0.0981880112352047), (3227, 0.09761623449529483), (1047, 0.09749269714016826), (4220, 0.09653797381048569), (3057, 0.09646780711467351), (4359, 0.09618629505643161), (2590, 0.09618383973992845), (3178, 0.09583940480154521), (1698, 0.09573115179904361), (561, 0.09465832883099422), (3430, 0.09459220242159563), (2405, 0.09442396529986785), (3171, 0.09390366074448347), (88, 0.09346747801567871), (2337, 0.09209500308819255), (2515, 0.09102174896256775), (873, 0.08937804621630929), (252, 0.08833852367185173), (424, 0.08791177200645697), (3463, 0.08781697279925853), (4406, 0.08722320987435406), (698, 0.08546991063727524), (3238, 0.08523238468059766), (4152, 0.0852309216133201), (268, 0.08501044330279128), (3644, 0.08457193260190782), (4076, 0.08431180919565923), (1363, 0.08369697330407005), (1802, 0.08367665046120107), (1895, 0.08347320509713876), (472, 0.08311718908112244), (1446, 0.08244580037243798), (1670, 0.08072510827691798), (125, 0.07979413625521037), (1855, 0.07896013555106782), (323, 0.07850400490905995), (241, 0.07823625196898071), (1920, 0.07810802344710727), (980, 0.07781213354262047), (3826, 0.07768221848693431), (3994, 0.07732298483136366), (828, 0.0773033404985867), (1334, 0.0769990578827697), (471, 0.07639828082217108), (3736, 0.0763183874287061), (3575, 0.07630306901106981), (2264, 0.07628282776888977), (273, 0.07599405469613213), (1118, 0.07588477622893303), (2424, 0.07586079632291456), (1490, 0.07580401062799527), (2125, 0.0757252887488101), (1304, 0.07554627103981099), (3643, 0.07478846508931458), (3351, 0.07439952416056154), (3202, 0.07435023474826798), (4078, 0.07393677426965298), (15, 0.07379273404541656), (254, 0.07375706095087892), (3142, 0.07336425402381304), (3723, 0.07220693671174995), (1207, 0.0719651379456343), (1564, 0.0717499743480892), (265, 0.07170427704517993), (2075, 0.0716991526046829), (830, 0.0716311063004192), (2153, 0.07131844716807462), (3837, 0.07120056724523462), (2068, 0.0710593107411518), (63, 0.07071062731134053), (169, 0.06987497411084885), (2635, 0.06980902071464155), (2288, 0.06976913603714988), (246, 0.06964112529834744), (4095, 0.06963134596265955), (3448, 0.06958624016481975), (3061, 0.0695470073881685), (3927, 0.06942213972767686), (350, 0.06917334159685709), (2888, 0.06908813453525785), (4773, 0.06898924025583486), (4129, 0.06891518840953004), (910, 0.06859689725176196), (1467, 0.06813457983714177), (3399, 0.06770251866861153), (1283, 0.0674949623353535), (145, 0.06715178909174155), (589, 0.06652475171876619), (3038, 0.06626533385221314), (1117, 0.06601808779328129), (846, 0.06549812295594354), (1095, 0.06540530189899649), (1644, 0.06528475909064341), (77, 0.06462588932048775), (1404, 0.06455969001606371), (1696, 0.06444883713805521), (4215, 0.06430492041050401), (4649, 0.06427300472940388), (2893, 0.06413623707337784), (1275, 0.06413554873074623), (3094, 0.06412935415961943), (2040, 0.06380441282521203), (4197, 0.06375839719285734), (1800, 0.0634146689117903), (2246, 0.06333960315822598), (3653, 0.06222439656916285), (324, 0.061357470132870184), (3705, 0.06127875432187922), (815, 0.06127494670840666), (946, 0.06124138555105861), (2748, 0.06104130456749335), (3754, 0.06100466212705019), (1573, 0.060631870056098325), (3356, 0.06050738333772338), (2013, 0.0603314092827885), (16, 0.06032902289210043), (70, 0.06021503695476884), (4335, 0.06013761785733058), (2946, 0.06001081411715365), (1076, 0.05980372352602376), (362, 0.05947441256955038), (813, 0.059223353330778605), (1198, 0.059221016472259684), (769, 0.058647199855299634), (55, 0.05793709201833548), (4172, 0.05789757611406503), (160, 0.057852579348617025), (1587, 0.057705431720759356), (558, 0.057304778904743905), (2086, 0.05708793088963828), (225, 0.05697260915734598), (2570, 0.05678338571151395), (1358, 0.05660453786293331), (2154, 0.056468891659518156), (289, 0.056460464342286076), (2725, 0.056452534594595954), (1284, 0.05450768042415865), (1825, 0.054458246182749186), (2990, 0.05434268610757229), (1892, 0.05380158697314931), (2032, 0.053614954251056605), (1314, 0.05335524494149921), (3671, 0.05317034105024311), (2047, 0.05315355227435449), (1778, 0.05314509362462773), (1907, 0.05313908867347963), (3106, 0.05287145525776374), (2190, 0.05284043089109709), (421, 0.052817682827589536), (193, 0.05279443255389024), (4020, 0.052677621346374985), (3088, 0.052631981257529034), (725, 0.052413262764472016), (85, 0.05229126880212534), (3495, 0.05209924497785181), (354, 0.05208647142401178), (137, 0.052045421173174775), (26, 0.05203687694293091), (1828, 0.052029228504755096), (1176, 0.05198685590103966), (683, 0.05177582652587938), (258, 0.05171349267331493), (215, 0.051675442911129375), (605, 0.051606313161643505), (2018, 0.05128665099615591), (824, 0.0510046919083801), (1110, 0.05095989465502559), (3032, 0.050774053938642476), (3899, 0.0505857288821739), (1980, 0.05019237213267386), (1062, 0.04966111952218916), (3728, 0.04965902394541512), (1299, 0.04959896387742006), (430, 0.049498913056555675), (865, 0.0493052076356565), (518, 0.04906468776035259), (2396, 0.0490099119964859), (7, 0.04892460741566832), (4320, 0.048879811375285784), (750, 0.0488317929563735), (2759, 0.048754719265332425), (2643, 0.04873301810344464), (538, 0.048471920215624485), (358, 0.04840786563528134), (3099, 0.04822178597797768), (1225, 0.04805036197022254), (336, 0.0479964144771496), (4371, 0.04796199207928964), (1478, 0.04781798828166822), (1728, 0.047440896638780795), (136, 0.04739209874605156), (1941, 0.04713330488328074), (744, 0.04711990174575753), (802, 0.047088977848753794), (455, 0.04706319753692716), (4532, 0.04686735804081066), (89, 0.04676601401327338), (2364, 0.04676144785410766), (288, 0.0464417586158937), (464, 0.04634345977622448), (4136, 0.04633233205873524), (4203, 0.04630810377777883), (3704, 0.04624475490011036), (1656, 0.04619687577010613), (866, 0.04612216403687367), (2699, 0.04605977723652772), (1795, 0.04604610950863239), (1703, 0.04593203738926821), (1664, 0.04575357139980689), (1286, 0.045748485166032304), (1282, 0.04561443760482773), (2197, 0.04556266587680379), (1742, 0.04550881775689647), (390, 0.045494373769219304), (2310, 0.04548888771608994), (2813, 0.045397892678432764), (2625, 0.04530494939674312), (3745, 0.04530245300144365), (3485, 0.04507177965801403), (4130, 0.04503308024474527), (1341, 0.044981862110764534), (1354, 0.044867326459350584), (1084, 0.04478258347300425), (734, 0.0446289931956782), (1841, 0.04433179249739993), (1970, 0.04427686962815247), (72, 0.044116371791294746), (3900, 0.04403332452173697), (896, 0.043916661792276615), (573, 0.04385030384843435), (4346, 0.04378357068673494), (2863, 0.04376267025283465), (2039, 0.043649930159702754), (1991, 0.04319177605972394), (525, 0.043190970734855866), (1181, 0.04318909049251287), (1277, 0.04301120899880198), (3810, 0.042917918930475946), (144, 0.042739019922208264), (1558, 0.04259730389063416), (2501, 0.0425361184950363), (4438, 0.04248803733479625), (2493, 0.042241339774267084), (1850, 0.04206800962582311), (453, 0.041971321025614246), (1086, 0.041910035123598366), (297, 0.04179098905484309), (3278, 0.041766808658891916), (1073, 0.041721023424887344), (4307, 0.04167473233905995), (1294, 0.041532052432605035), (2674, 0.04141893788496121), (4033, 0.04131797447501713), (2335, 0.04112175809228377), (1835, 0.04111680845511914), (428, 0.04106874568584698), (1955, 0.04104576626981399), (1366, 0.04096819465510498), (2321, 0.04091240706146982), (1615, 0.040881167277145185), (2443, 0.040862456972460874), (3211, 0.04081302131174554), (2455, 0.04075944054593321), (506, 0.04069213166314051), (2997, 0.04064862277846122), (387, 0.040614826004665504), (1144, 0.040597170848024985), (3080, 0.04056947177532954), (1101, 0.04056860238812681), (4326, 0.04042835104719178), (66, 0.04030865861361299), (4396, 0.04015175234446666), (607, 0.039991609044506875), (1058, 0.03996503131221962), (2480, 0.03989315073050567), (3406, 0.03985026385051729), (1702, 0.03974367814963163), (4644, 0.039672621174709884), (3494, 0.03940612381579364), (4235, 0.039309426735665336), (1672, 0.03919875262951422), (4292, 0.03917491112111073), (652, 0.03917403864612788), (2653, 0.039166935484019796), (504, 0.03907280517911368), (283, 0.03904684812825703), (4603, 0.0389665776423411), (2353, 0.03896143429173447), (37, 0.038830950826118996), (1083, 0.03879941415741398), (1777, 0.038714575475304686), (4675, 0.03871223945404008), (1001, 0.03865397156224597), (3507, 0.03865247067682297), (488, 0.038634191248674774), (150, 0.03862762446454644), (3706, 0.038612980915066576), (2804, 0.03860139931235613), (1418, 0.03860026073742005), (3993, 0.03859305295250272), (3230, 0.038582285591824354), (238, 0.03852088100256574), (3859, 0.0384358043157709), (4747, 0.038423591018140385), (2072, 0.03806934954467696), (411, 0.03804421653044088), (3559, 0.03798121173405938), (99, 0.0379801020002844), (591, 0.037873994161303985), (1767, 0.037861036154983575), (3364, 0.0377752405938031), (2280, 0.037724157709109356), (1535, 0.03770529841194241), (3425, 0.03769844383500318), (4128, 0.037678849552987836), (3772, 0.03765122880810666), (3603, 0.03758098292259477), (797, 0.0375298168301539), (501, 0.037527828560371373), (1114, 0.03739710972651403), (4752, 0.037383549332204606), (3622, 0.03738058804395472), (1939, 0.03727003521354316), (3105, 0.03717078997016692), (92, 0.0371698365413029), (2852, 0.0371230194887317), (1856, 0.037095069364867006), (2270, 0.03703773211798614), (2322, 0.03700776669479762), (2842, 0.03697446388874364), (545, 0.036972961969711046), (2203, 0.03694518467538947), (1279, 0.036937470952490135), (3785, 0.03690157261543495), (34, 0.03685749073266727), (2843, 0.036820986717843576), (1937, 0.03681343075760673), (4251, 0.03680512768111823), (1082, 0.03678850433611514), (257, 0.036752847991546524), (4513, 0.03673840326315729), (3631, 0.036727021428409855), (870, 0.036707078569287746), (1133, 0.036651523225265895), (0, 0.036567934745542055), (3305, 0.03654649490863383), (1257, 0.03653997773157872), (86, 0.03644578123248539), (342, 0.03643104192583434), (872, 0.03637277294326652), (631, 0.03634381794941033), (1695, 0.03618435951678814), (728, 0.03616182473839242), (142, 0.036096654299524945), (2294, 0.03604647067331026), (3271, 0.03597897763490422), (950, 0.035947060250127234), (3583, 0.03591328508820657), (4120, 0.03590357196736055), (3805, 0.03589544948282738), (942, 0.03562447561114765), (971, 0.035606883999575484), (877, 0.03558109712160531), (1682, 0.03555636761180038), (1297, 0.035502790427246786), (714, 0.035462575937792076), (4088, 0.035436174542930424), (4533, 0.03540270618819619), (2229, 0.035370409029387165), (2124, 0.03536753660086082), (1375, 0.035328034280601286), (1197, 0.03530321647571156), (40, 0.0352904381178987), (3008, 0.03526117026985578), (2921, 0.03525451038845004), (3292, 0.03523608063921056), (503, 0.03521547257148008), (186, 0.03516038282664128), (33, 0.03515431131858308), (3934, 0.03505908479500859), (393, 0.03504280296003437), (2388, 0.03503293691166863), (1191, 0.03499396507238409), (367, 0.03493739779340704), (4493, 0.03490294993050401), (4541, 0.034868600834696305), (565, 0.034817139540390535), (1837, 0.03475667046784424), (2346, 0.03472945232413203), (2376, 0.03465192032247153), (2768, 0.03463729102631764), (1170, 0.03461507069164889), (3973, 0.03457871956566746), (742, 0.03457606641224402), (1586, 0.03455708696697271), (10, 0.034536185238873675), (234, 0.034531475653876646), (3062, 0.034524914373286274), (1376, 0.03451158532504913), (755, 0.03450942908750583), (1078, 0.034475535220615874), (106, 0.034460898933957804), (2578, 0.034309897731909955), (2049, 0.034307769195541286), (2805, 0.034275671887760845), (3614, 0.03417626312500291), (641, 0.03416881182792873), (2301, 0.03413320539480663), (190, 0.034102870201350985), (2218, 0.034047526391240895), (2955, 0.03400370263584395), (3001, 0.03399317174242238), (1034, 0.033961769119383686), (2379, 0.03391192786478505), (2173, 0.03390602232110122), (899, 0.0338885984958634), (2691, 0.03385463064337728), (1562, 0.033726136301288734), (1303, 0.033712809602008995), (2779, 0.03370750270385663), (867, 0.03368844195837249), (2899, 0.0336795749870071), (3242, 0.03366870822390859), (2814, 0.033613736021883514), (240, 0.03357864025746912), (1781, 0.03356589700591262), (2099, 0.03353758338148158), (569, 0.033533611076877155), (359, 0.03352210617570377), (956, 0.03348977854196846), (534, 0.03333989779959329), (4229, 0.033334895603081456), (2179, 0.03333480471548712), (1915, 0.03331273345931935), (704, 0.03328945644598954), (4014, 0.03328886521736197), (2939, 0.03326972693746467), (3328, 0.03324926404182078), (3343, 0.03320425398388255), (3326, 0.03319022905448927), (4721, 0.033145831739812504), (703, 0.03313029245694807), (4298, 0.033107905760845456), (1230, 0.03302393267059929), (1287, 0.03302116598888795), (2158, 0.032946654677822165), (507, 0.03294356854484835), (459, 0.032911715739987656), (1607, 0.032910958609400305), (3760, 0.032903922938376025), (2698, 0.032901737243549486), (1266, 0.03288008419135911), (2823, 0.03286781490292727), (1156, 0.032840740927268935), (2175, 0.03283971463681657), (133, 0.032776516351229676), (4561, 0.032749999908550965), (1431, 0.03264487607243416), (2733, 0.03262464973163528), (2490, 0.032610909550366954), (583, 0.03260776038824508), (3291, 0.03258645547395865), (202, 0.03248438883278803), (3591, 0.032429312404902835), (668, 0.03241923796737748), (3033, 0.03239227541954236), (245, 0.032386658653451174), (3969, 0.032341176122329625), (1335, 0.03227395245866163), (325, 0.03224265494833865), (2712, 0.03223043685729012), (584, 0.032184374812820306), (2368, 0.032022392536248945), (2544, 0.03199017918854592), (2145, 0.031981756676153945), (3694, 0.0319702941365522), (3981, 0.03196824916453359), (604, 0.031938728395718555), (2694, 0.0318940255512254), (2390, 0.031875348941479316), (3122, 0.0318540675329135), (2176, 0.03183437475191035), (4454, 0.031832576821503034), (1291, 0.03182854341428372), (263, 0.031816677106650884), (1229, 0.03179746114639014), (887, 0.03172245526042785), (4286, 0.031720401301589034), (1984, 0.03171743243492706), (203, 0.0316457713889701), (1553, 0.031621015604971214), (1550, 0.03162001470356107), (521, 0.03154624767995607), (3659, 0.0315206693719714), (3831, 0.031513281398452705), (1357, 0.031417360840975656), (1105, 0.031357148673347573), (4629, 0.03124062620499318), (4671, 0.03119131515633528), (581, 0.031182680121275973), (3285, 0.031163448287431002), (3681, 0.03113006576751723), (516, 0.031120792315859853), (1729, 0.031092997555880016), (2100, 0.03106029284455863), (2114, 0.031004872718174044), (4401, 0.03099545622223136), (3841, 0.030954031755276085), (4800, 0.030914327964931675), (3165, 0.030912893147517932), (2156, 0.030828780123944), (3234, 0.030795886873370655), (566, 0.030771061752945174), (4576, 0.030764593102028642), (3572, 0.030758276354803896), (2251, 0.030736783863377803), (4471, 0.030675946330130006), (2670, 0.03062584341710769), (1675, 0.030525753263056316), (1524, 0.030504511961714914), (1374, 0.030434335762786285), (3617, 0.03041089654635174), (14, 0.030406237651804384), (1816, 0.030361106901340387), (4046, 0.0303273864487357), (1401, 0.030267345305083782), (2476, 0.03024482147810314), (3025, 0.030229160618365516), (854, 0.030225426212835988), (4612, 0.03022143960247387), (1718, 0.030218395936501337), (3988, 0.030199069749443853), (339, 0.03018314773421396), (4392, 0.030180312914279177), (1506, 0.030159125647022757), (57, 0.030140269338107466), (777, 0.030115236210633237), (953, 0.03010932814185482), (374, 0.030104212232678416), (923, 0.030101875689025732), (4144, 0.030100962829658483), (4613, 0.030089572479879517), (2005, 0.03008264075695129), (3454, 0.030068814027583702), (391, 0.0299752030573652), (3955, 0.029940323820351562), (4463, 0.029895402673048237), (934, 0.02985062822676917), (2871, 0.02983616375774057), (3939, 0.0298278498209723), (44, 0.029811825424671767), (2763, 0.029794191305858767), (2892, 0.029734478799963753), (4601, 0.029710937175468403), (1513, 0.029707086413128508), (1416, 0.029657991666018953), (3942, 0.029656068178251702), (2717, 0.02957932157746891), (858, 0.029540151485335203), (2681, 0.029527539606684687), (1900, 0.02952628834846694), (439, 0.029520466048179293), (294, 0.02951807826527335), (479, 0.029501099112579275), (4085, 0.029470264245395297), (3639, 0.029468515125920886), (699, 0.02944967872822912), (3208, 0.0294485039121267), (1097, 0.02942827183922358), (17, 0.029415932026375408), (3615, 0.029371519547782825), (4631, 0.02933593186699213), (361, 0.029321952277855255), (3975, 0.029300188541358765), (4467, 0.029286431707421907), (1232, 0.029281179217701785), (3004, 0.029276573224907683), (75, 0.02920551804362095), (539, 0.029187512273087954), (447, 0.029143823074542854), (1629, 0.029121962408017184), (3403, 0.029097239314897733), (368, 0.029088138601639946), (18, 0.029074356769414753), (2600, 0.029047741552164077), (814, 0.02901117232551206), (1280, 0.028890405404561104), (300, 0.028819337455082094), (1999, 0.02877754314979375), (173, 0.02877674165049432), (2172, 0.02877494419670484), (4611, 0.028752991529986154), (962, 0.028752448826628325), (3344, 0.02871965787895936), (2701, 0.02866926088865777), (3978, 0.028665092430146595), (2669, 0.028642773393770023), (4345, 0.028619621767218977), (1641, 0.028598952810538043), (3012, 0.028588103618681804), (3901, 0.028556726550446308), (1227, 0.02851432117910525), (221, 0.02850957891472617), (2803, 0.02843487197029546), (67, 0.028414312685192823), (3209, 0.02840329947119127), (328, 0.028400838523027654), (4764, 0.0283729422801064), (4049, 0.02835678766891047), (676, 0.028342408208399394), (422, 0.028336115219557822), (1093, 0.02832563011625515), (4678, 0.028311198161163606), (2850, 0.02830218108486813), (117, 0.02827941461095332), (1516, 0.028273472104082886), (1556, 0.028237177076946767), (347, 0.028211730188412155), (1602, 0.028181945175394105), (6, 0.028180303704604732), (302, 0.02817805198094639), (2491, 0.028148969544982947), (1745, 0.02812026960224543), (1541, 0.02811854532076189), (1817, 0.02809119376796363), (2793, 0.028083781255181725), (657, 0.02807950492948594), (2469, 0.02806337357168613), (4791, 0.028001303785193925), (4198, 0.02799944850775498), (1944, 0.02798397606181882), (1162, 0.02797848573104527), (321, 0.027912732175345303), (1983, 0.02789044992512844), (73, 0.027864776210409673), (4695, 0.02782676408423672), (179, 0.02780338826891044), (164, 0.027791490858306657), (1580, 0.027786805556044653), (3072, 0.027742868120213024), (848, 0.027727098484188), (2234, 0.02771357365416964), (1046, 0.02767622340469361), (4311, 0.027601631618906504), (340, 0.027598384322517332), (2305, 0.027553060963181178), (2714, 0.027550458145500854), (4572, 0.027550241000730565), (3204, 0.027548067736867687), (1300, 0.02754411697867396), (141, 0.02754014229422056), (3352, 0.02753446403229664), (3391, 0.027495532204424467), (370, 0.027479031336666012), (305, 0.02746149988350033), (460, 0.02745744572547887), (2185, 0.027375211429916273), (279, 0.02736318240350771), (951, 0.02727276504299076), (2504, 0.02724892789985445), (3350, 0.027199223010729922), (4222, 0.027073500790831564), (2204, 0.02704238014426892), (3413, 0.027002311305571024), (3937, 0.02696

In [26]:
print("Movies suggested for you :\n")
i=1
for movie in sorted_similar_movies:
    index = movie[0]
    title_from_index = movies_data[movies_data.index == index]['title'].values[0]
    if(i<30):
        print(i, '.', title_from_index)
        i+=1

Movies suggested for you :

1 . TMNT
2 . Southland Tales
3 . Out of the Furnace
4 . Ratatouille
5 . Scooby-Doo
6 . Super Mario Bros.
7 . Veronika Decides to Die
8 . Ride Along
9 . The Man Who Knew Too Little
10 . Austin Powers in Goldmember
11 . Simply Irresistible
12 . Prince of Persia: The Sands of Time
13 . Happily N'Ever After
14 . Money Train
15 . Meet Dave
16 . Harvard Man
17 . Brothers
18 . Scooby-Doo 2: Monsters Unleashed
19 . Finding Forrester
20 . Kung Fu Panda
21 . Kung Fu Panda 3
22 . The Grudge
23 . Rumble in the Bronx
24 . Scream 2
25 . Ride Along 2
26 . From Dusk Till Dawn
27 . Batman Begins
28 . Napoleon Dynamite
29 . Cruel Intentions

SUMMING UP

In [27]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_data[movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

 Enter your favourite movie name : batman
Movies suggested for you :

1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . Batman Begins
5 . Man of Steel
6 . Beetlejuice
7 . Mars Attacks!
8 . Superman Returns
9 . Jonah Hex
10 . The Dark Knight Rises
11 . Superman III
12 . Bedazzled
13 . A History of Violence
14 . Reds
15 . I Dreamed of Africa
16 . The Dark Knight
17 . Superman
18 . Something's Gotta Give
19 . Exorcist II: The Heretic
20 . Superman II
21 . Blood and Wine
22 . The New Guy
23 . Catwoman
24 . 8 Mile
25 . Nine 1/2 Weeks
26 . Batman
27 . Batman Forever
28 . Multiplicity
29 . Cellular